services:
  maroodi.api:
    image: ${DOCKER_REGISTRY-}maroodiapi
    build:
      context: .
      dockerfile: Maroodi/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"

  postgresql:
    image: postgres:18
    environment:
      POSTGRES_USER: maroodi
      POSTGRES_PASSWORD: maroodi_password
      POSTGRES_DB: maroodi_db
    ports:
      - "5432:5432"