"""add amount to store_products

Revision ID: 48030886ba81
Revises: ca6a24ef0108
Create Date: 2026-04-25 03:04:23.462231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '48030886ba81'
down_revision: Union[str, None] = 'ca6a24ef0108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_products', sa.Column('amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_products', 'amount')
    # ### end Alembic commands ###