"""add amount to products

Revision ID: b35f5f9d92a9
Revises: 48030886ba81
Create Date: 2026-04-25 19:23:13.704251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b35f5f9d92a9'
down_revision: Union[str, None] = '48030886ba81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('amount', sa.Float(), nullable=True))
    op.drop_column('store_products', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_products', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('products', 'amount')
    # ### end Alembic commands ###