"""Remove price from Products

Revision ID: c2672c3fa47f
Revises: f389f5b2d3de
Create Date: 2026-05-02 21:22:36.653019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c2672c3fa47f'
down_revision: Union[str, None] = 'f389f5b2d3de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###