"""add unit to products

Revision ID: ca6a24ef0108
Revises: f5e7176b089e
Create Date: 2026-04-25 02:54:02.508332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ca6a24ef0108'
down_revision: Union[str, None] = 'f5e7176b089e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('unit', sa.String(length=20), nullable=False))
    op.drop_column('store_products', 'stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_products', sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('products', 'unit')
    # ### end Alembic commands ###