"""Rename sku to barcode

Revision ID: f389f5b2d3de
Revises: b35f5f9d92a9
Create Date: 2026-05-02 21:06:44.636855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f389f5b2d3de'
down_revision: Union[str, None] = 'b35f5f9d92a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('barcode', sa.String(length=100), nullable=False))
    op.drop_constraint(op.f('products_sku_key'), 'products', type_='unique')
    op.create_unique_constraint(None, 'products', ['barcode'])
    op.drop_column('products', 'sku')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='unique')
    op.create_unique_constraint(op.f('products_sku_key'), 'products', ['sku'], postgresql_nulls_not_distinct=False)
    op.drop_column('products', 'barcode')
    # ### end Alembic commands ###