services:
  maroodi.api:
    image: ${DOCKER_REGISTRY-}maroodiapi
    build:
      context: .
      dockerfile: Maroodi/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgresql;Database=maroodi_db;Port=5432;Username=maroodi;Password=maroodi_password;SSL Mode=Disable;
    depends_on:
      - postgresql

  postgresql:
    image: postgres:18
    environment:
      POSTGRES_USER: maroodi
      POSTGRES_PASSWORD: maroodi_password
      POSTGRES_DB: maroodi_db
    ports:
      - "5432:5432"